/**
 * @description       : 
 * @author            : Abishek ND
 * @last modified on  : 06-18-2025
 * @last modified by  : Abishek ND
**/
public class OopsClass {
		Private String message;
    /**
    * @description 
    * @author Abishek ND | 06-18-2025 
    * @param String message 
    * @return String 
    **/
    public String displayMessage(String message){
        this.message=message;
        return this.message;
    }
    /**
    * @description 
    * @author Abishek ND | 06-18-2025 
    **/
    public void displayMessage(){
        system.debug(message);
    }
    /**
    * @description 
    * @author Abishek ND | 06-18-2025 
    * @param List<String> str 
    * @return List<String> 
    **/
    public List<String> retrunString(List<String> str){
       		return str;
    }

    Public void getnumbers(){

    }
}