/**
 * @description       : 
 * @author            : Abishek ND
 * @last modified on  : 06-13-2025
 * @last modified by  : Abishek ND
**/
public class OopsClass {
		Private String message;
    public String displayMessage(String message){
        this.message=message;
        return this.message;
    }
    public void displayMessage(){
        system.debug(message);
    }
    public List<String> retrunString(List<String> str){
       		return str;
    }

    Public void getnumbers(){

    }
}